name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run shell
        run: |
          go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: ./  # 指定正确的工作目录
          args: --verbose  # 显示详细日志

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # 指定你的Go版本
          cache: true # 启用内置缓存，默认为true
      - name: Download dependencies
        run: |
          go version
          go mod download
          
      - name: Build
        run: |
          go build -o main main.go
          ls
